export const EDdataMA = [
    {
        "Facility Name": "HEALTH ALLIANCE HOSPITAL-LEOMINSTER",
        "Address": "60 HOSPITAL ROAD",
        "City": "LEOMINSTER",
        "State": "MA",
        "ZIP Code": "01453",
        "County": "WORCESTER",
        "Telephone Number": "(978) 466-2000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospitals",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "ACE MEDICAL SERVICES",
        "Address": "40 SPRUCE ST",
        "City": "LEOMINSTER",
        "State": "MA",
        "ZIP Code": "01453",
        "County": "WORCESTER",
        "Telephone Number": "(978) 840-8900",
        "Hours": "Open 24 Hours",
        "ED Volume": "N/A",
        "Hospital Type": "Nursing Home",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "RELIANT MEDICAL GROUP",
        "Address": "5 NEPONSET ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01606",
        "County": "WORCESTER",
        "Telephone Number": "(508) 368-7800",
        "Hours": "7:15 AM - 5:15 PM",
        "ED Volume": "N/A",
        "Hospital Type": "Multi-specialty",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "BRADBURY MICHEAL J",
        "Address": "50 MEMORIAL DR #107",
        "City": "LEOMINSTER",
        "State": "MA",
        "ZIP Code": "01453",
        "County": "WORCESTER",
        "Telephone Number": "(978) 537-4800",
        "Hours": "9AM - 5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "EMERSON HOSPITAL LONGVIEW CORPORATE CENTER",
        "Address": "80 ERDMAN WAY",
        "City": "LEOMINSTER",
        "State": "MA",
        "ZIP Code": "01453",
        "County": "WORCESTER",
        "Telephone Number": "(978) 466-3408",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "NORTH ATLANTIC MEDICAL",
        "Address": "125 TOLMAN AVE",
        "City": "LEOMINSTER",
        "State": "MA",
        "ZIP Code": "01453",
        "County": "WORCESTER",
        "Telephone Number": "(978) 840-0113",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "SPECTRUM HEALTH SYSTEMS",
        "Address": "585 LINCOLN ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01605",
        "County": "WORCESTER",
        "Telephone Number": "(508) 854-3320",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MOUNT AUBURN HOSPITAL",
        "Address": "330 MOUNT AUBURN STREET",
        "City": "CAMBRIDGE",
        "State": "MA",
        "ZIP Code": "02138",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 492-3500",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "CAMBRIDGE HOSPITAL",
        "Address": "1493 CAMBRIDGE STREET",
        "City": "CAMBRIDGE",
        "State": "MA",
        "ZIP Code": "02138",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 665-2300",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "SPAULDING HOSPITAL CAMBRIDGE",
        "Address": "1575 CAMBRIDGE STREET",
        "City": "CAMBRIDGE",
        "State": "MA",
        "ZIP Code": "02138",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 876-4344",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "HARVARD UNIVERSITY HEALTH SERVICE",
        "Address": "75 MT AUBURN ST",
        "City": "CAMBRIDGE",
        "State": "MA",
        "ZIP Code": "02138",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 495-5711",
        "Hours": "8:30AM - 5:30 PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CHARLES RIVER GYROTONIC",
        "Address": "300 WESTERN AVE",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02134",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 254-1656",
        "Hours": "9AM - 5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CAMBRIDGE EATING DISORDER CENTER",
        "Address": "3 BOW STREET",
        "City": "CAMBRIDGE",
        "State": "MA",
        "ZIP Code": "02138",
        "County": "MIDDLESEX",
        "Telephone Number": "(888) 900-2332",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "YOUVILLE LIFECARE",
        "Address": "1573 CAMBRIDGE ST",
        "City": "CAMBRIDGE",
        "State": "MA",
        "ZIP Code": "02138",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 491-1234",
        "Hours": "9AM - 5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MAEL CHIROPRACTIC",
        "Address": "1 BRAINTREE ST",
        "City": "ATTELBORO",
        "State": "MA",
        "ZIP Code": "02138",
        "County": "SUFFOLK",
        "Telephone Number": "(617)787-8700",
        "Hours": "9AM-6:30PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "D R MEDICAL",
        "Address": "51 PARK ST",
        "City": "ATTELBORO",
        "State": "MA",
        "ZIP Code": "02703",
        "County": "BRISTOL",
        "Telephone Number": "(508) 222-1972",
        "Hours": "9AM-4PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "ARBOUR-FULLER HOSPITAL",
        "Address": "200 MAY STREET",
        "City": "SOUTH ATTELBORO",
        "State": "MA",
        "ZIP Code": "02703",
        "County": "BRISTOL",
        "Telephone Number": "(508) 761-8500",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "Psychiatric",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "MEMORIAL HOSPITAL",
        "Address": "211 PARK ST",
        "City": "ATTELBORO",
        "State": "MA",
        "ZIP Code": "02703",
        "County": "BRISTOL",
        "Telephone Number": "(508) 222-5200",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "LAWRENCE GENERAL HOSPITAL",
        "Address": "ONE GENERAL STREET",
        "City": "LAWRENCE",
        "State": "MA",
        "ZIP Code": "01842",
        "County": "ESSEX",
        "Telephone Number": "(978) 683-4000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "CARITAS HOLY FAMILY HOSPITAL",
        "Address": "70 EAST STREET",
        "City": "METHUEN",
        "State": "MA",
        "ZIP Code": "01844",
        "County": "ESSEX",
        "Telephone Number": "(978) 687-0156",
        "Hours": "Not Available",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "GREATER LAWRENCE MENTAL HEALTH CENTER",
        "Address": "34 HAVERHILL ST",
        "City": "LAWRENCE",
        "State": "MA",
        "ZIP Code": "01840",
        "County": "ESSEX",
        "Telephone Number": "(978) 686-0090",
        "Hours": "8AM - 8:30PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MAESTRO CONNECTIONS HEALTH SYSTEMS",
        "Address": "439 S UNION #209",
        "City": "LAWRENCE",
        "State": "MA",
        "ZIP Code": "01843",
        "County": "ESSEX",
        "Telephone Number": "(978) 794-1158",
        "Hours": "9AM - 5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "DSI NORTH ANDOVER",
        "Address": "201 SUTTON STREET",
        "City": "NORTH ANDOVER",
        "State": "MA",
        "ZIP Code": "01845",
        "County": "ESSEX",
        "Telephone Number": "(833) 412-2378",
        "Hours": "6AM - 9PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "YANKEE ALLIANCE",
        "Address": "138 RIVER RD",
        "City": "ANDOVER",
        "State": "MA",
        "ZIP Code": "01810",
        "County": "ESSEX",
        "Telephone Number": "(978) 470-2000",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "SAINTS MEDICAL CENTER",
        "Address": "1 HOSPITAL DR",
        "City": "LOWELL",
        "State": "MA",
        "ZIP Code": "01852",
        "County": "MIDDLESEX",
        "Telephone Number": "(978) 458-1411",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CAPE COD HEALTHCARE",
        "Address": "27 PARK STREET",
        "City": "HYANNIS",
        "State": "MA",
        "ZIP Code": "02601",
        "County": "BARNSTABLE",
        "Telephone Number": "(508) 771-1800",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "MEDICAL SERVICE AMBULANCE",
        "Address": "372 YARMOUTH RD",
        "City": "HYANNIS",
        "State": "MA",
        "ZIP Code": "02601",
        "County": "BARNSTABLE",
        "Telephone Number": "(508) 694-6687",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "COOLEY DICKINSON HOSPITAL ",
        "Address": "30 LOCUST STREET",
        "City": "NORTHAMPTON",
        "State": "MA",
        "ZIP Code": "01060",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 582-2000",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "SERVICENET",
        "Address": "50 PLEASANT ST",
        "City": "NORTHAMPTON",
        "State": "MA",
        "ZIP Code": "01060",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 584-6855",
        "Hours": "9AM - 7PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "WESTERN MASS EMERGENCY",
        "Address": "168 INDUSTRIAL DR",
        "City": "NORTHAMPTON",
        "State": "MA",
        "ZIP Code": "01060",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 586-6065",
        "Hours": "9AM - 5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "ON CALL URGENT CARE CENTER",
        "Address": "6 HATFIELD ST",
        "City": "NORTHAMPTON",
        "State": "MA",
        "ZIP Code": "01060",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 584-7425",
        "Hours": "9AM - 7PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "PHYSICAL OCCUPATIONAL THERAPY",
        "Address": "10 MAIN ST",
        "City": "NORTHAMPTON",
        "State": "MA",
        "ZIP Code": "01062",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 584-5760",
        "Hours": "8AM - 4PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "THE COMPULSIVE GAMBLING TREATMENT PROGRAM",
        "Address": "76 PLEASANT ST",
        "City": "NORTHAMPTON",
        "State": "MA",
        "ZIP Code": "01060",
        "County": "HAMPSHIRE",
        "Telephone Number": "(888) 311-3043",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "NORTHAMPTON VA MEDICAL CENTER",
        "Address": "421 N MAIN ST",
        "City": "LEEDS",
        "State": "MA",
        "ZIP Code": "01053",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 584-4040",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "Acute Care - Veterans Administration",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "BAYSTATE FRANKLIN MEDICAL CENTER",
        "Address": "164 HIGH STREET",
        "City": "GREENFIELD",
        "State": "MA",
        "ZIP Code": "01301",
        "County": "FRANKLIN",
        "Telephone Number": "(413) 773-0211",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospitals",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "WESTERN MASS TRAINING CONSORTUM",
        "Address": "187 HIGH ST #202",
        "City": "HOLYOKE",
        "State": "MA",
        "ZIP Code": "01040",
        "County": "HAMPDEN",
        "Telephone Number": "(413) 536-2401",
        "Hours": "8:30AM-4:30PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "TAPESTRY HEALTH SYSTEM",
        "Address": "76 CARLON DR",
        "City": "NORTHAMPTON",
        "State": "MA",
        "ZIP Code": "01060",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 586-2539",
        "Hours": "9AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "FRANKLIN MEDICAL CENTER",
        "Address": "1280 W CENTRAL ST SUITE 103",
        "City": "FRANKLIN",
        "State": "MA",
        "ZIP Code": "02038",
        "County": "NORFOLK",
        "Telephone Number": "(508) 528-2700",
        "Hours": "7:30AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CONCENTRA",
        "Address": "140 CARANDO DR",
        "City": "SPRINGFIELD",
        "State": "MA",
        "ZIP Code": "01104",
        "County": "HAMPDEN",
        "Telephone Number": "(413) 746-4006",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CARITAS CARNEY HOSPITAL",
        "Address": "2100 DORCHESTER AVENUE",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02124",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 506-2000",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "KIT CLARK SENIOR SERVICES",
        "Address": "1500 DORCHESTER AVE",
        "City": "DORCHESTER",
        "State": "MA",
        "ZIP Code": "02122",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 825-5000",
        "Hours": "8:30AM - 7PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "HARVARD STREET TEEN CLINIC",
        "Address": "632 BLUE HILL AVE",
        "City": "DORCHESTER",
        "State": "MA",
        "ZIP Code": "02121",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 825-3400",
        "Hours": "8:30AM-8PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "PHAN AN T",
        "Address": "1370 DORCHESTER AVE #23",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02122",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 288-8883",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MATTAPAN COMMUNITY HEALTH CENTER",
        "Address": "1575 BLUE HILL AVE",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02126",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 296-0061",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "BOSTON CITY COMMUNITY CENTERS PROGRAM",
        "Address": "409 W BROADWAY ",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02127",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 296-7500",
        "Hours": "8:30AM-7PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "LEMUEL SHATTUCK HOSPITAL",
        "Address": "170 MORTON ST",
        "City": "JAMAICA PLAIN",
        "State": "MA",
        "ZIP Code": "02130",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 522-8110",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "LIFEHOUSE",
        "Address": "1 WESTINGHOUSE PLAZA",
        "City": "HYDE PARK",
        "State": "MA",
        "ZIP Code": "02136",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 910-9605",
        "Hours": "9AM-6PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "RADIUS SPECIALTY",
        "Address": "59 TOWNSEND STREET",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02119",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 989-8400",
        "Hours": "11AM-8PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "HARINGTON MEMORIAL HOSPITAL",
        "Address": "100 SOUTH STREET",
        "City": "SOUTHBRIDGE",
        "State": "MA",
        "ZIP Code": "01550",
        "County": "WORCESTER",
        "Telephone Number": "(508) 765-9771",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "SRC MAIN STREET",
        "Address": "181 MAIN ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01605",
        "County": "WORCESTER",
        "Telephone Number": "(774) 701-0764",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "HOSPITAL SPA",
        "Address": "151 SOUTH ST",
        "City": "SOUTHBRIDGE",
        "State": "MA",
        "ZIP Code": "01550",
        "County": "WORCESTER",
        "Telephone Number": "(508) 764-6780",
        "Hours": "8AM-4:30PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "PAIN MANAGEMENT CLINIC",
        "Address": "116 BELMONT ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01605",
        "County": "WORCESTER",
        "Telephone Number": "(508) 713-6063",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "EVERYBODYS FITNESS CENTER",
        "Address": "441 SOUTHBRIDGE ST",
        "City": "AUBURN",
        "State": "MA",
        "ZIP Code": "01501",
        "County": "WORCESTER",
        "Telephone Number": "(508) 832-3700",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "SAINT ANNE'S HOSPITAL",
        "Address": "795 MIDDLE STREET",
        "City": "FALL RIVER",
        "State": "MA",
        "ZIP Code": "02721",
        "County": "BRISTOL",
        "Telephone Number": "(508) 674-5600",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "BARBARA SOARES MD",
        "Address": "49 HILLSIDE STREET",
        "City": "FALL RIVER",
        "State": "MA",
        "ZIP Code": "02720",
        "County": "BRISTOL",
        "Telephone Number": "(508) 235-7600",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "Psychiatric",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "HOLYOKE MEDICAL CENTER",
        "Address": "575 BEECH STREET",
        "City": "HOLYOKE",
        "State": "MA",
        "ZIP Code": "01040",
        "County": "HAMPDEN",
        "Telephone Number": "(413) 534-2500",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "ANNA JAQUES HOSPITAL",
        "Address": "25 HIGHLAND AVENUE",
        "City": "NEWBURYPORT",
        "State": "MA",
        "ZIP Code": "01950",
        "County": "ESSEX",
        "Telephone Number": "(978) 463-1000",
        "Hours": "Open 24 Hours",
        "ED Volume": "low",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "BOSTON MEDICAL CENTER",
        "Address": "1 BOSTON MEDICAL CENTER PLACE",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02118",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 638-8000",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "TUFTS MEDICAL CENTER",
        "Address": "800 WASHINGTON STREET",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02111",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 636-5000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "WESTWOOD-PEMBROKE HEALTH SYSTEMS",
        "Address": "45 CLAPBOARDTREE STREET",
        "City": "WESTWOOD",
        "State": "MA",
        "ZIP Code": "02090",
        "County": "NORFOLK",
        "Telephone Number": "(617) 762-7764",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "Psychiatric",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "NORTH SHORE MEDICAL CENTER -",
        "Address": "81 HIGHLAND AVENUE",
        "City": "SALEM",
        "State": "MA",
        "ZIP Code": "01970",
        "County": "ESSEX",
        "Telephone Number": "(978) 741-1215",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "ST. ELIZABETH'S MEDICAL CENTER",
        "Address": "736 CAMBRIDGE STREET",
        "City": "BRIGHTON",
        "State": "MA",
        "ZIP Code": "02135",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 789-3000",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "FRANCISCAN HOSPITAL FOR CHILDREN",
        "Address": "30 WARREN STREET",
        "City": "BRIGHTON",
        "State": "MA",
        "ZIP Code": "02135",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 254-3800",
        "Hours": "8:30AM-5PM",
        "ED Volume": "Not Available",
        "Hospital Type": "Childrens",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "BETH ISRAEL DEACONESS MEDICAL CENTER",
        "Address": "330 BROOKLINE AVENUE",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02215",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 667-7000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "BEAR HEALTH SYSTEMS",
        "Address": "59 ACTON ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01604",
        "County": "WORCESTER",
        "Telephone Number": "(508) 791-3147",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "BOSTON THE CENTER PARTIAL HOSPITAL PROGRAM",
        "Address": "14 FORDHAM RD",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02134",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 783-9676",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "BERKSHIRE MEDICAL CENTER",
        "Address": "725 NORTH STREET",
        "City": "PITTSFIELD",
        "State": "MA",
        "ZIP Code": "01201",
        "County": "BERKSHIRE",
        "Telephone Number": "(413) 447-2000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "BERKSHIRE HEALTH SYSTEMS LAB",
        "Address": "188 EAST ST",
        "City": "PITTSFIELD",
        "State": "MA",
        "ZIP Code": "01201",
        "County": "BERKSHIRE",
        "Telephone Number": "(413) 997-4460",
        "Hours": "7:30AM-4PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "GASTROENTEROLOGY AT BERKSHIRE HEALTH SYSTEMS",
        "Address": "41 WAHCONAH ST",
        "City": "PITTSFIELD",
        "State": "MA",
        "ZIP Code": "01201",
        "County": "BERKSHIRE",
        "Telephone Number": "(413) 499-8575",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "BERKSHIRE PHYSICIANS & SURGEONS PC",
        "Address": "777 NORTH ST",
        "City": "PITTSFIELD",
        "State": "MA",
        "ZIP Code": "01201",
        "County": "BERKSHIRE",
        "Telephone Number": "(413) 445-6420",
        "Hours": "8AM-4:30PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "HILLCREST CAMPUS OF BERKSHIRE MEDICAL CENTER",
        "Address": "631 NORTH ST",
        "City": "PITTSFIELD",
        "State": "MA",
        "ZIP Code": "01201",
        "County": "BERKSHIRE",
        "Telephone Number": "(413) 499-2051",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "HILLCREST HOSPITAL",
        "Address": "165 TOR CT",
        "City": "PITTSFIELD",
        "State": "MA",
        "ZIP Code": "01201",
        "County": "B",
        "Telephone Number": "(413) 447-2862",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MARLBOROUGH HOSPITAL",
        "Address": "157 UNION STREET",
        "City": "MARLBOROUGH",
        "State": "MA",
        "ZIP Code": "01752",
        "County": "MIDDLESEX",
        "Telephone Number": "(508) 481-5000",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "SIGNATURE HEALTHCARE",
        "Address": "680 CENTER STREET",
        "City": "BROCKTON",
        "State": "MA",
        "ZIP Code": "02302",
        "County": "PLYMOUTH",
        "Telephone Number": "(508) 941-7000",
        "Hours": "8AM - 8PM",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospitals",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "ADCARE HOSPITAL OF WORCESTER ",
        "Address": "107 LINCOLN STREET",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01605",
        "County": "WORCESTER",
        "Telephone Number": "(508) 799-9000",
        "Hours": "Open 24 Hours",
        "ED Volume": "Not Available",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "LOWELL GENERAL HOSPITAL",
        "Address": "295 VARNUM AVENUE",
        "City": "LOWELL",
        "State": "MA",
        "ZIP Code": "01854",
        "County": "MIDDLESEX",
        "Telephone Number": "(978) 937-6000",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "MERCY MEDICAL CENTER",
        "Address": "271 CAREW STREET",
        "City": "SPRINGFIELD",
        "State": "MA",
        "ZIP Code": "01104",
        "County": "HAMPDEN",
        "Telephone Number": "(413) 748-9000",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "SHRINERS HOSPITAL FOR CHILDREN-SPRINGFIELD",
        "Address": "516 CAREW STREET",
        "City": "SPRINGFIELD",
        "State": "MA",
        "ZIP Code": "01104",
        "County": "HAMPDEN",
        "Telephone Number": "(413) 787-2000",
        "Hours": "8AM - 4:30PM",
        "ED Volume": "Not Available",
        "Hospital Type": "Childrens",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "WELDON REHABILITATION HOSPITAL",
        "Address": "175 CAREW ST",
        "City": "SPRINGFIELD",
        "State": "MA",
        "ZIP Code": "01104",
        "County": "HAMPDEN",
        "Telephone Number": "(413) 748-6880",
        "Hours": "7AM-8PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "BASS SPINE AND REHABILITATION",
        "Address": "57 E MAIN ST",
        "City": "WESTBOROUGH",
        "State": "MA",
        "ZIP Code": "01581",
        "County": "WORCESTER",
        "Telephone Number": "(508) 898-0144",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "BAYSTATE MEDICAL CENTER",
        "Address": "759 CHESTNUT STREET",
        "City": "SPRINGFIELD",
        "State": "MA",
        "ZIP Code": "01199",
        "County": "HAMPDEN",
        "Telephone Number": "(413) 794-0000",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "Acute Care Hospitals",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "MELROSE WAKEFIELD HEALTHCARE",
        "Address": "585 LEBANON STREET",
        "City": "MELROSE",
        "State": "MA",
        "ZIP Code": "02176",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 979-3000",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "DOCTOR S EXPRESS",
        "Address": "38 BOSTON POST RD W",
        "City": "MARLBOROUGH",
        "State": "MA",
        "ZIP Code": "01752",
        "County": "MIDDLESEX",
        "Telephone Number": "(508) 658-0764",
        "Hours": "8AM-8PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "SHRINERS' HOSPITAL FOR CHILDREN - BOSTON",
        "Address": "51 BLOSSOM STREET",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02114",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 722-3000",
        "Hours": "Open 24 Hours",
        "ED Volume": "Not Available",
        "Hospital Type": "Childrens",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MASSACHUSETTS GENERAL HOSPITAL",
        "Address": "55 FRUIT STREET",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02114",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 724-9725",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "MORTON HOSPITAL AND MEDICAL CENTER",
        "Address": "88 WASHINGTON STREET",
        "City": "TAUNTON",
        "State": "MA",
        "ZIP Code": "02780",
        "County": "BRISTOL",
        "Telephone Number": "(508) 828-7000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "HOWELL JAS B",
        "Address": "72 WASHINGTON ST",
        "City": "TAUNTON",
        "State": "MA",
        "ZIP Code": "02780",
        "County": "BRISTOL",
        "Telephone Number": "(508) 880-3460",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "TAUNTON REGIONAL PAIN MEDICINE CENTER",
        "Address": "1 WASHINGTON ST",
        "City": "TAUNTON",
        "State": "MA",
        "ZIP Code": "02780",
        "County": "BRISTOL",
        "Telephone Number": "(508) 824-1259",
        "Hours": "7:30AM-4PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "TAUNTON STATE HOSPITAL",
        "Address": "60 HODGES AVENUE, BOX 151",
        "City": "TAUNTON",
        "State": "MA",
        "ZIP Code": "02780",
        "County": "BRISTOL",
        "Telephone Number": "(508) 97-3000",
        "Hours": "9AM-5PM",
        "ED Volume": "",
        "Hospital Type": "Psychiatric",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "PEDIATRICS SUB-SPECIALTY",
        "Address": "475 FRANKLIN ST STE 209",
        "City": "FRAMINGHAM",
        "State": "MA",
        "ZIP Code": "01702",
        "County": "MIDDLESEX",
        "Telephone Number": "(508) 875-5189",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "OCCUPATIONAL HEALTH SERVICES AT NORWOODS MEDICAL",
        "Address": "95 CHAPEL ST #3A",
        "City": "NORWOOD",
        "State": "MA",
        "ZIP Code": "02062",
        "County": "NORFOLK",
        "Telephone Number": "(781) 769-3113",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "SOUTHCOAST HOSPITALS GROUP",
        "Address": "363 HIGHLAND AVENUE",
        "City": "FALL RIVER",
        "State": "MA",
        "ZIP Code": "02720",
        "County": "BRISTOL",
        "Telephone Number": "(508) 679-3131",
        "Hours": "9AM - 4PM",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "BETH ISRAEL DEACONESS HOSPITAL-NEEDHAM",
        "Address": "148 CHESTNUT STREET",
        "City": "NEEDHAM",
        "State": "MA",
        "ZIP Code": "02494",
        "County": "NORFOLK",
        "Telephone Number": "(781) 453-3002",
        "Hours": "Open 24 Hours",
        "ED Volume": "low",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "NEWTON-WELLESLEY HOSPITAL",
        "Address": "2014 WASHINGTON STREET",
        "City": "NEWTON",
        "State": "MA",
        "ZIP Code": "02462",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 243-6000",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "EMERSON HOSPITAL",
        "Address": "133 OLD ROAD TO 9 ACRE CORNER",
        "City": "W CONCORD",
        "State": "MA",
        "ZIP Code": "01742",
        "County": "MIDDLESEX",
        "Telephone Number": "(978) 369-1400",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "BEDFORD VA HOSPITAL",
        "Address": "200 SPRINGS ROAD",
        "City": "BEDFORD",
        "State": "MA",
        "ZIP Code": "01730",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 275-7500",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "Acute Care - Veterans Administration",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "NEB HOSPITAL",
        "Address": "125 PARKER HILL AVENUE",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02120",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 754-5800",
        "Hours": "Open 24 Hours",
        "ED Volume": "Not Available",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "BRIGHAM AND WOMEN'S HOSPITAL",
        "Address": "75 FRANCIS STREET",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02115",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 732-5500",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "MILFORD REGIONAL MEDICAL CENTER",
        "Address": "14 PROSPECT STREET",
        "City": "MILFORD",
        "State": "MA",
        "ZIP Code": "01757",
        "County": "WORCESTER",
        "Telephone Number": "(508) 473-1190",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "GAMMA SONICS",
        "Address": "170 DUTCHER ST",
        "City": "HOPEDALE",
        "State": "MA",
        "ZIP Code": "01747",
        "County": "WORCESTER",
        "Telephone Number": "(508) 478-7894",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "AMERICAN MEDICAL SERVICE",
        "Address": "4 INDUSTRIAL RD",
        "City": "MILFORD",
        "State": "MA",
        "ZIP Code": "01757",
        "County": "WORCESTER",
        "Telephone Number": "(508) 473-9800",
        "Hours": "8:30AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "TRI COUNTY MEDICAL ASSOCIATES",
        "Address": "327 WEST ST",
        "City": "MILFORD",
        "State": "MA",
        "ZIP Code": "01757",
        "County": "WORCESTER",
        "Telephone Number": "(508) 634-9962",
        "Hours": "8AM-8PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "HEYWOOD MEMORIAL HOSPITAL",
        "Address": "242 GREEN STREET",
        "City": "GARDNER",
        "State": "MA",
        "ZIP Code": "01440",
        "County": "WORCESTER",
        "Telephone Number": "(978) 632-3420",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "NORTH CENTRAL CORRECTIONS INSTITUTE",
        "Address": "500 COLONY RD",
        "City": "GARDNER",
        "State": "MA",
        "ZIP Code": "01440",
        "County": "WORCESTER",
        "Telephone Number": "(978) 630-6000",
        "Hours": "9AM-3:30PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "NASHOBA VALLEY MEDICAL CENTER",
        "Address": "200 GROTON ROAD",
        "City": "AYER",
        "State": "MA",
        "ZIP Code": "01432",
        "County": "MIDDLESEX",
        "Telephone Number": "(978) 784-9000",
        "Hours": "Open 24 Hours",
        "ED Volume": "low",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "GENESIS HEALTHCARE",
        "Address": "44 KEYSTONE DR",
        "City": "LEOMINSTER",
        "State": "MA",
        "ZIP Code": "01453",
        "County": "WORCESTER",
        "Telephone Number": "(978) 537-9327",
        "Hours": "7:30AM-9PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "GROTON WELLNESS",
        "Address": "493 MAIN ST",
        "City": "GROTON",
        "State": "MA",
        "ZIP Code": "01450",
        "County": "MIDDLESEX",
        "Telephone Number": "(978) 449-919",
        "Hours": "7AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MASSACHUSETTS EYE AND EAR INFIRMARY",
        "Address": "243 CHARLES STREET",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02114",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 523-7900",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "SOUTH SHORE HOSPITAL",
        "Address": "55 FOGG ROAD",
        "City": "SOUTH WEYMOUTH",
        "State": "MA",
        "ZIP Code": "02190",
        "County": "NORFOLK",
        "Telephone Number": "(781) 340-8000",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "ATRIUS WOMENS CENTER",
        "Address": "51 PERFORMANCE DR",
        "City": "WEYMOUTH",
        "State": "MA",
        "ZIP Code": "02189",
        "County": "NORFOLK",
        "Telephone Number": "(781) 682-8000",
        "Hours": "7:30AM-6PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "WINCHESTER HOSPITAL",
        "Address": "41 HIGHLAND AVENUE",
        "City": "WINCHESTER",
        "State": "MA",
        "ZIP Code": "01890",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 729-9000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CARITAS GOOD SAMARITAN MEDICAL CENTER",
        "Address": "235 NORTH PEARL STREET",
        "City": "BROCKTON",
        "State": "MA",
        "ZIP Code": "02301",
        "County": "PLYMOUTH",
        "Telephone Number": "(508) 427-3000",
        "Hours": "8AM - 8PM",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "FAULKNER HOSPITAL",
        "Address": "1153 CENTRE STREET",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02130",
        "County": "SUFFOLK",
        "Telephone Number": "(617) 983-7000",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "ARBOUR HOSPITAL",
        "Address": "49 ROBINWOOD AVENUE",
        "City": "BOSTON",
        "State": "MA",
        "ZIP Code": "02130",
        "County": "AUFFOLK",
        "Telephone Number": "(617) 522-4400",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "Psychiatric",
        "Emergency Services": "No"
    },
    {
        "Facility Name": "NORWOOD HOSPITAL",
        "Address": "800 WASHINGTON STREET",
        "City": "NORWOOD",
        "State": "MA",
        "ZIP Code": "02062",
        "County": "NORFOLK",
        "Telephone Number": "(781) 769-4000",
        "Hours": "8AM -8PM",
        "ED Volume": "Not Available",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "WESTWOOD DIALYSIS CENTER",
        "Address": "90 GLACIER DR",
        "City": "WESTWOOD",
        "State": "MA",
        "ZIP Code": "02090",
        "County": "NORFOLK",
        "Telephone Number": "(800) 881-5101",
        "Hours": "5AM-8PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CARITAS HOSPITALS",
        "Address": "29 CRAFTS ST ",
        "City": "NEWTON",
        "State": "MA",
        "ZIP Code": "02458",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 964-7530",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "VISIONS HEALTHCARE",
        "Address": "100 GROVE ST SUITE 103",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01605",
        "County": "WORCESTER",
        "Telephone Number": "(508) 250-8378",
        "Hours": "9AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "FALMOUTH HOSPITAL",
        "Address": "67 & 100 TER HEUN DRIVE",
        "City": "FALMOUTH",
        "State": "MA",
        "ZIP Code": "02540",
        "County": "BARNSTABLE",
        "Telephone Number": "(508) 548-5300",
        "Hours": "Open 24 Hours",
        "ED Volume": "medium",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "ASAP MEDICAL SERVICES",
        "Address": "10 BRAMBLE BUSH DR",
        "City": "FALMOUTH",
        "State": "MA",
        "ZIP Code": "02540",
        "County": "BARNSTABLE",
        "Telephone Number": "(508) 548-2402",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "FAXON CENTER",
        "Address": "100 TER HEUN DR",
        "City": "FALMOUTH",
        "State": "MA",
        "ZIP Code": "02540",
        "County": "BARNSTABLE",
        "Telephone Number": "(508) 457-3964",
        "Hours": "7AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "UMASS MEDICAL CENTER MEMORIAL CAMPUS",
        "Address": "119 BELMONT ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01605",
        "County": "WORCESTER",
        "Telephone Number": "(508) 334-1000",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "UMASS MEMORIAL MEDICAL CENTER",
        "Address": "55 LAKE AVENUE NORTH",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01655",
        "County": "WORCESTER",
        "Telephone Number": "(508) 334-1000",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "WORCESTER MEDICAL CENTER",
        "Address": "123 SUMMER ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01605",
        "County": "WORCESTER",
        "Telephone Number": "(508) 852-0600",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "LAHEY HOSPITAL & MEDICAL CENTER, BURLINGTON",
        "Address": "41 & 45 MALL ROAD",
        "City": "BURLINGTON",
        "State": "MA",
        "ZIP Code": "01803",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 744-5100",
        "Hours": "Open 24 Hours",
        "ED Volume": "very high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "INSTITUTE OF ORTHOPEDIC MANUAL THERAPY",
        "Address": "334 COLLEGE ST",
        "City": "AMHERST",
        "State": "MA",
        "ZIP Code": "01002",
        "County": "HAMPSHIRE",
        "Telephone Number": "(413) 992-2131",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "SOLARUS ENTERPRISES",
        "Address": "281 CAMBRIDGE ST",
        "City": "BURLINGTON",
        "State": "MA",
        "ZIP Code": "01803",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 272-8888",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "LAHEY CLINIC ",
        "Address": "41 BURLINGTON MALL ROAD",
        "City": "BURLINGTON",
        "State": "MA",
        "ZIP Code": "01805",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 744-5100",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "ATRIUS HEALTH",
        "Address": "275 GROVE ST",
        "City": "NEWTON",
        "State": "MA",
        "ZIP Code": "02466",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 559-8000",
        "Hours": "8:30AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "METROPOLITAN BOSTON EMERGENCY MEDICAL SERVICES",
        "Address": "25 B STRETT",
        "City": "BURLINGTON",
        "State": "MA",
        "ZIP Code": "01803",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 505-4367",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "MASSACHUSETTS HOSPITAL ASSOCIATION",
        "Address": "500 DISTRICT AVE",
        "City": "BURLINGTON",
        "State": "MA",
        "ZIP Code": "01803",
        "County": "MIDDLESEX",
        "Telephone Number": "(781) 262-6000",
        "Hours": "Not Available",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "METROWEST MEDICAL CENTER",
        "Address": "115 LINCOLN STREET",
        "City": "FRAMINGHAM",
        "State": "MA",
        "ZIP Code": "01701",
        "County": "MIDDLESEX",
        "Telephone Number": "(508) 383-1000",
        "Hours": "Open 24 Hours",
        "ED Volume": "high",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "CANNAMED OF BOSTON",
        "Address": "475 FRANKLIN ST STE 205",
        "City": "FRAMINGHAM",
        "State": "MA",
        "ZIP Code": "01702",
        "County": "MIDDLESEX",
        "Telephone Number": "(866) 624-1191",
        "Hours": "9AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "ADVANTAGE HEALTH & WELLNESS",
        "Address": "188 CONCORD ST",
        "City": "FRAMINGHAM",
        "State": "MA",
        "ZIP Code": "01702",
        "County": "MIDDLESEX",
        "Telephone Number": "(508) 875-9693",
        "Hours": "9AM-7PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "THOM CHILD & FAMILY CLINIC",
        "Address": "1661 WORCESTER RD",
        "City": "FRAMINGHAM",
        "State": "MA",
        "ZIP Code": "01701",
        "County": "MIDDLESEX",
        "Telephone Number": "(508) 655-5222",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "SPECTRUM HEALTH  ",
        "Address": "50 HOWE AVE",
        "City": "MILLBURY",
        "State": "MA",
        "ZIP Code": "01527",
        "County": "WORCESTER",
        "Telephone Number": "(508) 865-2085",
        "Hours": "5:30AM-7PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CENTURY HEALTH SYSTEMS",
        "Address": "65 WATER DT",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01604",
        "County": "WORCESTER",
        "Telephone Number": "(508) 762-4040",
        "Hours": "9AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "DOCTORS EXPRESS",
        "Address": "376 ARSENAL ST",
        "City": "WATERTOWN",
        "State": "MA",
        "ZIP Code": "02472",
        "County": "MIDDLESEX",
        "Telephone Number": "(617) 923-2273",
        "Hours": "8AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "CEDAR STREET FAMILY CLINIC",
        "Address": "390 MAIN ST",
        "City": "WORCESTER",
        "State": "MA",
        "ZIP Code": "01608",
        "County": "WORCESTER",
        "Telephone Number": "(508) 752-1331",
        "Hours": "9AM-4PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "NANTUCKET COTTAGE HOSPITAL",
        "Address": "57 PROSPECT STREET",
        "City": "NANTUCKET",
        "State": "MA",
        "ZIP Code": "02554",
        "County": "NANTUCKET",
        "Telephone Number": "(508) 228-1200",
        "Hours": "Open 24 Hours",
        "ED Volume": "low",
        "Hospital Type": "Acute Care Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "MARTHA'S VINEYARD HOSPITAL",
        "Address": "1 HOSPITAL RD",
        "City": "OAK BLUFFS",
        "State": "MA",
        "ZIP Code": "02557",
        "County": "DUKES",
        "Telephone Number": "(508) 693-0410",
        "Hours": "Open 24 Hours",
        "ED Volume": "low",
        "Hospital Type": "Critical Access Hospital",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "VINEYARD MEDICAL SERVICES",
        "Address": "364 STATE RD",
        "City": "VINEYARD HAVEN",
        "State": "MA",
        "ZIP Code": "02568",
        "County": "DUKES",
        "Telephone Number": "(508) 693-4400",
        "Hours": "8AM-4PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "ATHOL MEMORIAL HOSPITAL",
        "Address": "2033 MAIN STREET",
        "City": "ATHOL",
        "State": "MA",
        "ZIP Code": "01331",
        "County": "WORCESTER",
        "Telephone Number": "(978) 249-3511",
        "Hours": "Open 24 Hours",
        "ED Volume": "low",
        "Hospital Type": "Critical Access Hospitals",
        "Emergency Services": "Yes"
    },
    {
        "Facility Name": "WESTBOROUGH STATE HOSPITAL",
        "Address": "300 FRIBERG PKWY",
        "City": "WESTBOROUGH",
        "State": "MA",
        "ZIP Code": "01581",
        "County": "WORCESTER",
        "Telephone Number": "(508) 329-6300",
        "Hours": "Open 24 Hours",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "RENOVOMD",
        "Address": "96 W MAIN ST",
        "City": "NORTHBOROUGH",
        "State": "MA",
        "ZIP Code": "01532",
        "County": "WORCESTER",
        "Telephone Number": "(508) 393-6398",
        "Hours": "9AM-5PM",
        "ED Volume": "",
        "Hospital Type": "",
        "Emergency Services": ""
    },
    {
        "Facility Name": "RICHER LIFE JOURNEY",
        "Address": "56 CENTRAL ST",
        "City": "SOUTHBOROUGH",
        "State": "MA",
        "ZIP Code": "01745",
        "County": "WORCESTER",
        "Telephone Number": "(978) 852-7456",
        "Hours": "8AM-10PM"
    }
]